name: CI

on:
  push:
    branches: 
      - 'main'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sword-fight:latest
